<?php
// FILE PATH: app/Services/AutoInvoiceService.php

namespace App\Services;

use App\Models\FailedInvoiceLog;
use App\Models\Orders;
use App\Models\OrderItem;
use App\Models\OrderItemDelivery;
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;

class AutoInvoiceService
{
    protected InvoicePricingService $pricingService;

    public function __construct(InvoicePricingService $pricingService)
    {
        $this->pricingService = $pricingService;
    }

    /**
     * Main entry point — called by the artisan command daily at 5PM.
     *
     * Logic:
     *  1. Find all active orders (exclude Cancelled + On Hold)
     *  2. For each order, find delivery IDs where:
     *       - order_item.supplier_confirms = 1
     *       - order_item.client_confirms   = 1
     *       - order_item_delivery.delivery_date = tomorrow
     *       - order_item_delivery.invoice_id IS NULL  (not already invoiced)
     *  3. If no qualifying deliveries → skip order
     *  4. Call InvoicePricingService::createInvoice() with those delivery IDs
     *  5. On failure → log one row per delivery into failed_invoice_logs
     *  6. Continue to next order regardless of failure
     *
     * @return array  Summary stats for the command output
     */
    public function run(): array
    {
        $tomorrow = Carbon::tomorrow()->toDateString();
        $runDate  = Carbon::today()->toDateString();

        $summary = [
            'orders_checked'   => 0,
            'orders_skipped'   => 0,   // no qualifying deliveries
            'invoices_created' => 0,
            'orders_failed'    => 0,
            'failures_logged'  => 0,
        ];

        // ── Step 1: Load all active orders ──
        // Exclude: Cancelled and On Hold (order_status field)
        // We check order_status — not workflow — as workflow tracks supply chain
        // state, while order_status tracks the lifecycle of the order itself.
        $orders = Orders::whereNotIn('order_status', ['Cancelled', 'On Hold'])
            ->whereNotIn('workflow', ['Cancelled'])  // also exclude workflow-cancelled
            ->with([
                'items' => function ($q) {
                    // Only load items where BOTH confirms are 1
                    $q->where('supplier_confirms', 1)
                      ->where('client_confirms', 1);
                },
                'items.deliveries' => function ($q) use ($tomorrow) {
                    // Only load deliveries for tomorrow that are not yet invoiced
                    $q->whereDate('delivery_date', $tomorrow)
                      ->whereNull('invoice_id');
                },
            ])
            ->get();

        $summary['orders_checked'] = $orders->count();

        foreach ($orders as $order) {
            // ── Step 2: Collect qualifying delivery IDs for this order ──
            $qualifyingDeliveryIds = [];

            // Track which delivery belongs to which item
            // so we can log them accurately on failure
            $deliveryToItemMap = [];  // delivery_id => order_item_id

            foreach ($order->items as $item) {
                foreach ($item->deliveries as $delivery) {
                    $qualifyingDeliveryIds[]            = $delivery->id;
                    $deliveryToItemMap[$delivery->id]   = $item->id;
                }
            }

            // ── Step 3: No qualifying deliveries → skip ──
            if (empty($qualifyingDeliveryIds)) {
                $summary['orders_skipped']++;
                Log::info("AutoInvoice: Order #{$order->id} skipped — no qualifying deliveries for {$tomorrow}");
                continue;
            }

            // ── Step 4: Create invoice via existing service ──
            try {
                $result = $this->pricingService->createInvoice(
                    order:       $order,
                    deliveryIds: $qualifyingDeliveryIds,
                    createdBy:   1,                         // System admin user
                    notes:       'Generated by Bot',
                    dueDate:     $tomorrow,                 // Due next day (delivery day)
                    discount:    0.00,
                );

                $invoice     = $result['invoice'];
                $xeroWarning = $result['xero_warning'];

                $summary['invoices_created']++;

                Log::info("AutoInvoice: Invoice #{$invoice->invoice_number} created for Order #{$order->id}", [
                    'delivery_ids' => $qualifyingDeliveryIds,
                    'total'        => $invoice->total_amount,
                    'xero_synced'  => is_null($xeroWarning),
                    'xero_warning' => $xeroWarning,
                ]);

                // If Xero failed, log it as a warning but don't count as failure
                // (local invoice was still created successfully)
                if ($xeroWarning) {
                    Log::warning("AutoInvoice: Xero sync failed for Invoice #{$invoice->invoice_number}", [
                        'order_id' => $order->id,
                        'warning'  => $xeroWarning,
                    ]);
                }

            } catch (\Throwable $e) {
                // ── Step 5: Log failure — one row per delivery ──
                // We log per-delivery so admin can see exactly which
                // deliveries were affected and retry them individually.
                $summary['orders_failed']++;

                foreach ($qualifyingDeliveryIds as $deliveryId) {
                    FailedInvoiceLog::create([
                        'order_id'               => $order->id,
                        'order_item_id'          => $deliveryToItemMap[$deliveryId] ?? null,
                        'order_item_delivery_id' => $deliveryId,
                        'reason'                 => $e->getMessage(),
                        'run_date'               => $runDate,
                    ]);

                    $summary['failures_logged']++;
                }

                Log::error("AutoInvoice: Failed to create invoice for Order #{$order->id}", [
                    'error'        => $e->getMessage(),
                    'delivery_ids' => $qualifyingDeliveryIds,
                    'trace'        => $e->getTraceAsString(),
                ]);

                // ── Step 6: Continue to next order ──
                continue;
            }
        }

        return $summary;
    }
}